services:
    data_collector.vcr:
        class:      VCR\VCRBundle\DataCollector\VCRDataCollector
        arguments:  [ '@vcr.logger' ]
        tags:
            - { name: data_collector, template: "VCRVCRBundle:Profiler:collector", id: "vcr_collector" }

    vcr.logger:
        class:  VCR\VCRBundle\VCR\Logger

    vcr.config:
        class: VCR\Configuration
        calls:
            - [ enableLibraryHooks, [ "%vcr.library_hooks%" ]]
            - [ enableRequestMatchers, [ "%vcr.request_matchers%" ] ]
            - [ setCassettePath, [ "%vcr.cassette.path%" ] ]
            - [ setStorage, [ "%vcr.cassette.type%" ] ]

    vcr.http_client:
        class: VCR\Util\HttpClient

    vcr.factory:
        class:          VCR\VCRFactory
        factory: [VCR\VCRFactory, getInstance]
        arguments:      [ '@vcr.config' ]

    vcr.recorder:
        class:      VCR\Videorecorder
        arguments:  [ '@vcr.config', '@vcr.http_client', '@vcr.factory' ]
        calls:
            - [ setEventDispatcher, [ '@event_dispatcher' ] ]
        public: true
